BOARD_TAG    = nano328
MONITOR_PORT = /dev/ttyUSB0

AVRDUDE_ISP_BAUDRATE=115200
USER_LIB_PATH = /home/$(USER)/Arduino/libraries/
ARDUINO_LIBS = Wire Etherkit_Si5351

u:	upload

include /usr/share/arduino/Arduino.mk
